# Form implementation generated from reading ui file 'c:\Users\georg\Desktop\Education\current semester\image-processing\Task 9\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.transform_image_label = LabelClickable(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transform_image_label.sizePolicy().hasHeightForWidth())
        self.transform_image_label.setSizePolicy(sizePolicy)
        self.transform_image_label.setText("")
        self.transform_image_label.setObjectName("transform_image_label")
        self.horizontalLayout.addWidget(self.transform_image_label)
        self.no_transform_image_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_transform_image_label.sizePolicy().hasHeightForWidth())
        self.no_transform_image_label.setSizePolicy(sizePolicy)
        self.no_transform_image_label.setText("")
        self.no_transform_image_label.setObjectName("no_transform_image_label")
        self.horizontalLayout.addWidget(self.no_transform_image_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 21))
        self.menubar.setObjectName("menubar")
        self.detector_menu = QtWidgets.QMenu(self.menubar)
        self.detector_menu.setObjectName("detector_menu")
        self.transforms_menu = QtWidgets.QMenu(self.menubar)
        self.transforms_menu.setObjectName("transforms_menu")
        self.utility_menu = QtWidgets.QMenu(self.menubar)
        self.utility_menu.setObjectName("utility_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionShi_Tomachi = QtGui.QAction(MainWindow)
        self.actionShi_Tomachi.setObjectName("actionShi_Tomachi")
        self.actionHarris = QtGui.QAction(MainWindow)
        self.actionHarris.setObjectName("actionHarris")
        self.actionAffine = QtGui.QAction(MainWindow)
        self.actionAffine.setObjectName("actionAffine")
        self.actionPerspective = QtGui.QAction(MainWindow)
        self.actionPerspective.setObjectName("actionPerspective")
        self.actionLoad_image = QtGui.QAction(MainWindow)
        self.actionLoad_image.setObjectName("actionLoad_image")
        self.detector_menu.addAction(self.actionShi_Tomachi)
        self.detector_menu.addAction(self.actionHarris)
        self.transforms_menu.addAction(self.actionAffine)
        self.transforms_menu.addAction(self.actionPerspective)
        self.utility_menu.addAction(self.actionLoad_image)
        self.menubar.addAction(self.detector_menu.menuAction())
        self.menubar.addAction(self.transforms_menu.menuAction())
        self.menubar.addAction(self.utility_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.actionLoad_image.triggered.connect(MainWindow.load_image)
        self.actionHarris.triggered.connect(MainWindow.show_harris_widget)
        self.actionShi_Tomachi.triggered.connect(MainWindow.show_tomachi_widget)
        self.actionPerspective.triggered.connect(MainWindow.show_perspective_widget)
        self.actionAffine.triggered.connect(MainWindow.show_affine_widget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.detector_menu.setTitle(_translate("MainWindow", "Detectors"))
        self.transforms_menu.setTitle(_translate("MainWindow", "Transformations"))
        self.utility_menu.setTitle(_translate("MainWindow", "Utility"))
        self.actionShi_Tomachi.setText(_translate("MainWindow", "Shi\n"
"Tomachi"))
        self.actionHarris.setText(_translate("MainWindow", "Harris"))
        self.actionAffine.setText(_translate("MainWindow", "Affine"))
        self.actionPerspective.setText(_translate("MainWindow", "Perspective"))
        self.actionLoad_image.setText(_translate("MainWindow", "Load image"))
from LabelClickable import LabelClickable
