# Form implementation generated from reading ui file 'c:\Users\georg\Desktop\test qt designer python\ui\Filter2DParametersWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(693, 211)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kernels_lcd = QtWidgets.QLCDNumber(Form)
        self.kernels_lcd.setObjectName("kernels_lcd")
        self.horizontalLayout.addWidget(self.kernels_lcd)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.kernels_slider = QtWidgets.QSlider(Form)
        self.kernels_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.kernels_slider.setObjectName("kernels_slider")
        self.verticalLayout_3.addWidget(self.kernels_slider)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.type_lcs = QtWidgets.QLCDNumber(Form)
        self.type_lcs.setObjectName("type_lcs")
        self.horizontalLayout_2.addWidget(self.type_lcs)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.type_slider = QtWidgets.QSlider(Form)
        self.type_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.type_slider.setObjectName("type_slider")
        self.verticalLayout.addWidget(self.type_slider)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delta_lcd = QtWidgets.QLCDNumber(Form)
        self.delta_lcd.setObjectName("delta_lcd")
        self.horizontalLayout_3.addWidget(self.delta_lcd)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.delta_slider = QtWidgets.QSlider(Form)
        self.delta_slider.setMaximum(9999)
        self.delta_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.delta_slider.setObjectName("delta_slider")
        self.verticalLayout_2.addWidget(self.delta_slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_4.addItem(spacerItem)

        self.retranslateUi(Form)
        self.kernels_slider.valueChanged['int'].connect(Form.on_change)
        self.type_slider.valueChanged['int'].connect(Form.on_change)
        self.delta_slider.valueChanged['int'].connect(Form.on_change)
        self.kernels_slider.valueChanged['int'].connect(self.kernels_lcd.display)
        self.type_slider.valueChanged['int'].connect(self.type_lcs.display)
        self.delta_slider.valueChanged['int'].connect(self.delta_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Kernels"))
        self.label_2.setText(_translate("Form", "Resilt image type"))
        self.label_3.setText(_translate("Form", "Delta"))
