# Form implementation generated from reading ui file 'c:\Users\georg\Desktop\Education\current semester\image-processing\Task 10\ui\TomachiWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TomachiWidget(object):
    def setupUi(self, TomachiWidget):
        TomachiWidget.setObjectName("TomachiWidget")
        TomachiWidget.resize(1562, 811)
        self.verticalLayout = QtWidgets.QVBoxLayout(TomachiWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_label = QtWidgets.QLabel(TomachiWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_label.sizePolicy().hasHeightForWidth())
        self.img_label.setSizePolicy(sizePolicy)
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.verticalLayout.addWidget(self.img_label)
        self.features_button = QtWidgets.QPushButton(TomachiWidget)
        self.features_button.setObjectName("features_button")
        self.verticalLayout.addWidget(self.features_button)

        self.retranslateUi(TomachiWidget)
        self.features_button.clicked.connect(TomachiWidget.show_features)
        QtCore.QMetaObject.connectSlotsByName(TomachiWidget)

    def retranslateUi(self, TomachiWidget):
        _translate = QtCore.QCoreApplication.translate
        TomachiWidget.setWindowTitle(_translate("TomachiWidget", "Form"))
        self.features_button.setText(_translate("TomachiWidget", "show_features"))
